name: Bug report
description: File a bug report
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: Steps to reproduce
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: Output of `automateai version`
  - type: textarea
    attributes:
      label: Logs
      render: shell


