name: Feature request
description: Suggest an idea
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What's the problem or use-case?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: What would you like to see happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: What alternatives have you considered?


