name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install dependencies (all extras)
        run: |
          uv sync --all-extras --dev
      - name: Ruff lint
        run: |
          uv run ruff check .
      - name: Ruff format check
        run: |
          uv run ruff format --check .
      - name: Type check (soft)
        run: |
          uv run mypy src/automateai || true
      - name: Tests
        run: |
          uv run pytest -q || true


